# Generated by Django 4.1 on 2022-08-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок поста')),
                ('content', models.TextField(verbose_name='Содержимое поста')),
                ('short_content', models.TextField(verbose_name='Короткое содержание')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Пост на сайте',
                'verbose_name_plural': 'Посты на сайте',
            },
        ),
    ]
